version: '1'
services:
    sql:
        container_name: dx_db
        # image: biarms/mysql:5.7.33-beta-circleci # mysql image that works with apple m1 chip
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'dx_user'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'dx_db'
        volumes:
            - dxsqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes: 
  dxsqldata: {}
