const DivbloxBase = require("divbloxjs/divblox");
const [EntityNamePascalCase]EndpointBase = require('divbloxjs/dx-code-gen/generated-base/endpoints/[EntityNameLowerCaseSplitted].endpoint-base');

/*
This entity endpoint was generated by the divbloxjs package generator.
*/
class [EntityNamePascalCase]Endpoint extends [EntityNamePascalCase]EndpointBase {
    /**
     * Initializes the result and declares the available operations
     * @param {DivbloxBase} dxInstance An instance of divbloxjs to allow for access to the app configuration
     */
    constructor(dxInstance = null) {
        super(dxInstance);
    }

    // TODO: Add implementations for each declared operation below
}

module.exports = [EntityNamePascalCase]Endpoint;